#!/usr/bin/env bash
# Constants for Ralph Loop

# Configuration constants
MAX_CHARS="${MAX_CHARS:-4000}"
MAX_LINES_FOR_TOOL_RESULT=4
DEFAULT_MODEL="claude-sonnet-4.5"

# Fun names for Ralph
RALPH_NAMES=(
  "YOLO RALPH COOKING"
  "RALPH IN THE MATRIX"
  "RALPH MODE: ACTIVATED"
  "RALPH.EXE RUNNING"
  "EMPLOYEE OF THE MONTH RALPH"
  "RALPH IS SPEEEEEEEEEED"
  "BUSINESS MONEY GETTING BURNED BY RAAAALLLPPPHHHHH"
  "CRACKHEAD RALPH TO THE RESCUE"
  "BUSINESSSSSSS ISS RAAAAALLLLPPPPHHHH"
  "RALPH: PROCESSING..."
  "RALPH COOKING SOME TOOOKKKEEENNNNN FOR BUSINESSSSSSS"
)
